server:
  port: 8080
spring:
  logging:
    level:
      org:
        springframework:
          security=DEBUG
  datasource:
    url: ${POSTGRES_HOST}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 2
    data-source-properties:
      prepareThreshold: 0
  profiles:
    active: default
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope: email, openid, profile
          azure:
            client-id: ${MSA_CLIENT_ID}
            client-secret: ${MSA_CLIENT_SECRET}
            redirect-uri: ${MSA_REDIRECT_URI}
        provider:
          google:
            issuer-uri: https://accounts.google.com
          azure:
            issuer-uri: https://login.microsoftonline.com/${MSA_TENANT_ID}/v2.0
external:
  jwt:
    key: ${JWT_KEY}
  base-url: ${DOMAIN_BASE_URL}

